config/routes.rb
Rails.application.routes.draw do
  mount Listings::Engine => "/listings"

  resources :projects, except: [:show]
  resources :organizations, except: [:new, :show]
  devise_for :users, :controllers => {:registrations => "registrations"}
  get "admin", to: 'projects#index'

  get 'sobre_la_plataforma', to: 'application#about', as: 'about'
  get "ods/:goal", to: 'sustainable_development_goals#detail', as: 'goal'
  get "proyectos", to: 'projects#public', as: 'public_projects'

  root 'projects#dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :organization
  has_many :project_goals, dependent: :destroy
  has_and_belongs_to_many :locations, dependent: :destroy
  has_and_belongs_to_many :populations, dependent: :destroy

  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true

  scope :published, -> { where(published: true) }
  scope :pending, -> { where(published: [false, nil]) }

  def for_goal?(id)
    project_goals.any? { |pg| pg.goal == id.to_i }
  end

  def self.apply(filters, page_size)
    search = published.eager_load(:organization).includes(:project_goals).includes(:locations).includes(:populations)
    search = search.where("organizations.accepted = ?", true)
    search = search.where("locations.name ILIKE (?)", "%#{filters.location}%") if filters.location.present?
    search = search.where("populations.name ILIKE (?)", "%#{filters.population}%") if filters.population.present?
    search = search.where("start_date >= ? AND start_date <= ?", "#{filters.start_date}-01-01", "#{filters.start_date}-12-31") if filters.start_date.present?
    search = search.where("end_date >= ? AND end_date <= ?", "#{filters.end_date}-01-01", "#{filters.end_date}-12-31") if filters.end_date.present?
    search = search.references(:project_goals).where("project_goals.goal = ?", filters.sustainable_development_goal.to_i) if filters.sustainable_development_goal.present?
    search = search.where("organizations.legally_formed = ?", filters.legally_formed) if filters.legally_formed.present?
    search = search.where("projects.name ILIKE (?)", "%#{filters.name}%") if filters.name.present?
    search = search.where("organizations.name ILIKE (?)", "%#{filters.organization}%") if filters.organization.present?
    ids = search.select("projects.id", "organization_id").map { |r| r.id }
    offset = (filters.page - 1) * page_size if filters.page.present?
    {results: where("projects.id IN (?)", ids).eager_load(:organization).includes(:project_goals).includes(:locations).includes(:populations).limit(page_size).offset(offset),
     total: where("projects.id IN (?)", ids).count()}
  end

  def self.categorization_by_sdg(projects)
    res = {sdg_counts: Hash.new(0), by_location: {}, by_population: {}}
    projects.each do |p|
      p.project_goals.each do |pg|
        res[:sdg_counts][pg.goal] += 1
        p.populations.each do |pop|
          res[:by_population][pop.name] = Hash.new(0) unless res[:by_population].has_key?(pop.name)
          res[:by_population][pop.name][pg.goal] += 1
        end
        p.locations.each do |loc|
          res[:by_location][loc.code] = Hash.new(0) unless res[:by_location].has_key?(loc.code)
          res[:by_location][loc.code][pg.goal] += 1
        end
      end
    end
    res
  end

  def self.categorization_by_location(projects)
    res = {location_counts: Hash.new(0), by_sdg: {}, by_population: {}}
    projects.each do |p|
      p.locations.each do |loc|
        res[:location_counts][loc.code] += 1
        p.populations.each do |pop|
          res[:by_population][pop.name] = Hash.new(0) unless res[:by_population].has_key?(pop.name)
          res[:by_population][pop.name][loc.code] += 1
        end
        p.project_goals.each do |pg|
          res[:by_sdg][pg.goal] = Hash.new(0) unless res[:by_sdg].has_key?(pg.goal)
          res[:by_sdg][pg.goal][loc.code] += 1
        end
      end
    end
    res
  end

  def self.categorization_by_organization(projects)
    res = {organization_counts: Hash.new(0), by_sdg: {}, by_location: {}, by_population: {}}
    projects.each do |p|
      p.organizations.each do |org|
        res[:organization_counts][org.name] += 1
        p.populations.each do |pop|
          res[:by_population][pop.name] = Hash.new(0) unless res[:by_population].has_key?(pop.name)
          res[:by_population][pop.name][org.name] += 1
        end
        p.project_goals.each do |pg|
          res[:by_sdg][pg.goal] = Hash.new(0) unless res[:by_sdg].has_key?(pg.goal)
          res[:by_sdg][pg.goal][org.name] += 1
        end
        p.locations.each do |loc|
          res[:by_location][loc.code] = Hash.new(0) unless res[:by_location].has_key?(loc.code)
          res[:by_location][loc.code][org.name] += 1
        end
      end
    end
    res
  end

  def self.categorization_by_population(projects)
    res = {population_counts: Hash.new(0), by_sdg: {}, by_location: {}}
    projects.each do |p|
      p.populations.each do |pop|
        res[:population_counts][pop.name] += 1
        p.project_goals.each do |pg|
          res[:by_sdg][pg.goal] = Hash.new(0) unless res[:by_sdg].has_key?(pg.goal)
          res[:by_sdg][pg.goal][pop.name] += 1
        end
        p.locations.each do |loc|
          res[:by_location][loc.code] = Hash.new(0) unless res[:by_location].has_key?(loc.code)
          res[:by_location][loc.code][pop.name] += 1
        end
      end
    end
    res
  end

  def self.categorization_by_upload_time(projects)
    res = {timeline_counts: Hash.new(0), by_sdg: {}, by_location: {}, by_population: {}}
    projects.each do |p|
      date = p.week_of_upload
      res[:timeline_counts][date] += 1
      p.populations.each do |pop|
        res[:by_population][pop.name] = Hash.new(0) unless res[:by_population].has_key?(pop.name)
        res[:by_population][pop.name][date] += 1
      end
      p.project_goals.each do |pg|
        res[:by_sdg][pg.goal] = Hash.new(0) unless res[:by_sdg].has_key?(pg.goal)
        res[:by_sdg][pg.goal][date] += 1
      end
      p.locations.each do |loc|
        res[:by_location][loc.code] = Hash.new(0) unless res[:by_location].has_key?(loc.code)
        res[:by_location][loc.code][date] += 1
      end
    end
    res[:timeline_counts] = res[:timeline_counts].to_a
    res[:by_sdg].each_pair { |k, v| res[:by_sdg][k] = v.to_a }
    res[:by_location].each_pair { |k, v| res[:by_location][k] = v.to_a }
    res[:by_population].each_pair { |k, v| res[:by_population][k] = v.to_a }
    res
  end

  def week_of_upload()
    date = created_at.beginning_of_week
    "#{date.year}-#{date.month}-#{date.day}"
  end

  def organizations
    @organization = Organization.all
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, except: [:public, :dashboard]
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :verify_ownership, only: [:edit, :update]

  # GET /projects
  # GET /projects.json
  def index
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    new_params = project_params
    new_params["project_goals"] = project_params["project_goals"]
        .map{|id| ProjectGoal.new(goal: id)} if project_params["project_goals"]
    @project = Project.new(new_params)
    @project.organization = current_user.organization

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: 'Se creó el proyecto' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    proj = set_publishing_status
    proj = parse_project_goals(proj)
    if @project.published && !current_user.is_admin
      proj[:published] = false
    end

    respond_to do |format|
      if @project.update(proj)
        format.html { redirect_to projects_path, notice: 'Se actualizó el proyecto' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Se eliminó el proyecto' }
      format.json { head :no_content }
    end
  end

  def public
    @filters = filters_from_params
    @page_size = 15
    result = Project.apply(@filters, @page_size)
    @projects = result[:results]
    @total = result[:total]
    @organizations = Organization.all.map {|org| org.name}
  end

  def dashboard
    all_projects = Project.published.includes(:project_goals).includes(:locations).includes(:populations).includes(:organization)
    latest_projects = all_projects.where("projects.created_at >= ?",3.months.ago)
    all_projects = all_projects.all
    @by_time = Project.categorization_by_upload_time(all_projects)
    @by_sdg = Project.categorization_by_sdg(all_projects)
    @by_population = Project.categorization_by_population(all_projects)
    @by_location = Project.categorization_by_location(latest_projects.all)

    @total = Project.count
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :organization_id, :start_date, :end_date, location_ids: [], population_ids: [], project_goals: [], filters: {})
    end

    def set_publishing_status
      pj = project_params
      if params[:commit] == "Publicar"
        pj[:published] = true
      elsif params[:commit] == "Ocultar al público"
        pj[:published] = false
      end
      pj
    end

    def parse_project_goals(proj_params)
      existing = @project.project_goals
      proj_params["project_goals"] = proj_params["project_goals"].map do |id|
        if found = existing.find{|pg| pg.goal == id}
          puts found
          found
        else
          ProjectGoal.new(project_id: @project.id, goal: id)
        end
      end if proj_params["project_goals"]
      proj_params
    end

    def filters_from_params
      ProjectFilter.new start_date: params[:start_date], end_date: params[:end_date], legally_formed: params[:legally_formed],
        location: params[:location], population: params[:population], name: params[:name], sustainable_development_goal: params[:sustainable_development_goal], organization: params[:organization],
        page: params[:page].try(:to_i) || 1
    end

    def verify_organization
      if !current_user.is_admin && !current_user.organization.accepted
        render 'organizations/not_authorized'
      end
    end

    def verify_ownership
      if !current_user.is_admin && current_user.organization != @project.organization
        head :forbidden
      end
    end
end

app/views/projects/_form.html.haml
.row
  = form_for @project, html: {class: "col s12"} do |f|
    - if @project.errors.any?
      #error_explanation
        %p= "No se pudo guardar por #{pluralize(@project.errors.count, "error")}"
        %ul
          - @project.errors.full_messages.each do |msg|
            %li= msg
    .row
      .input-field.col.s12.m6
        = active_label(f, :name, @project)
        = f.text_field :name
    - if current_user.admin
      .row
        .input-field.col.s12.m6
          = f.label :organization_id, class: 'active'
          = f.collection_select(:organization_id, Organization.all, :id, :name)
    .row
      .input-field.col.s12.m6
        = active_label(f, :description, @project)
        = f.text_area :description, class: "materialize-textarea"
    .row
      .input-field.col.s12.m6
        = active_label(f, :location_ids, @project)
        = f.collection_select(:location_ids, Location.all, :id, :name, {prompt: "Elegir"}, {multiple: true})
    .row
      .input-field.col.s12.m6
        = active_label(f, :population_ids, @project)
        = f.collection_select(:population_ids, Population.all, :id, :name, {prompt: "Elegir"}, {multiple: true})
    .row
      .input-field.col.s6.m3
        = active_label(f, :start_date, @project)
        = f.text_field :start_date, class: 'datepicker', value: @project.start_date.try(:strftime,"%d/%m/%Y")
      .input-field.col.s6.m3
        = active_label(f, :end_date, @project)
        = f.text_field :end_date, class: 'datepicker', value: @project.end_date.try(:strftime,"%d/%m/%Y")
    .row
      .input-field.col.s12.m6= f.label :project_goals
    .row
      .input-field
        .col.s6.m3
          - SustainableDevelopmentGoal.all[0..8].each do |goal|
            %p
              = check_box_tag "project[project_goals][]", goal.number, @project.for_goal?(goal.number), id: "project_goals_#{goal.number}"
              %label{for: "project_goals_#{goal.number}"}
                - inline_sdg(goal)
        .col.s6.m3
          - SustainableDevelopmentGoal.all[9..16].each do |goal|
            %p
              = check_box_tag "project[project_goals][]", goal.number, @project.for_goal?(goal.number), id: "project_goals_#{goal.number}"
              %label{for: "project_goals_#{goal.number}"}
                - inline_sdg(goal)
    .row
      .col.s6
        = f.submit 'Guardar cambios', class: 'btn btn-large'
        - if current_user.is_admin
          - if @project.published
            = f.submit 'Ocultar al público', class: 'btn btn-large danger', :data => { :confirm => '¿Bajar este proyecto del sitio público?' }
          - else
            = f.submit 'Publicar', class: 'btn btn-large danger', :data => { :confirm => '¿Publicar proyecto en el sitio público?' } if current_user.is_admin
        = link_to 'Volver', projects_path, class: "btn btn-flat btn-large"

app/views/projects/_public_projects_page.haml
.count= pluralize(total, "proyecto")
- projects.each do |project|
  - org = project.organization
  .row.project-line
    .col.l2.hide-on-med-and-down
      = image_tag "/uploads/#{org.logo}", class: "org-logo" if org.logo
    .col.l7.m8.s12
      .row#title
        .col.s12
          .title= project.name
          .organization
            de
            = org.name
      .row
        .col.s12.sdgs
          - project.project_goals.map{|pg| pg.sustainable_development_goal }.each do |goal|
            - pp_sdg(goal)
      .row
        .col.s12
          = project.description
      .row.project-details
        .col.s4
          %i.material-icons location_on
          = names_for(project.locations)
        .col.s4
          %i.material-icons people
          = names_for(project.populations)
        .col.s4
          %i.material-icons today
          - if project.start_date.try(:year) == project.end_date.try(:year)
            = project.start_date.try(:year)
          - else
            = project.start_date.try(:year)
            \-
            = project.end_date.try(:year)
      .row
        .col.s12
          %p Compartir en:
          %p #{social_share_button_tag(project, desc: project.name)}

    #contact-details.col.l3.m4.hide-on-small-only
      - unless org.email.blank?
        .row
          .col.s12
            %i.material-icons email
            = org.email
      - unless org.telephone_number.blank?
        .row
          .col.s12
            %i.material-icons phone
            = org.telephone_number
      - unless org.twitter.blank?
        .row
          .col.s12
            %i.extra-icons.twitter
            = org.twitter
      - unless org.facebook.blank?
        .row
          .col.s12
            %i.extra-icons.facebook
            = org.facebook

:css
  .social-share-button .ssb-icon {
    background-size: 28px 28px;
    height: 28px;
    width: 28px;
  }

app/views/projects/dashboard.haml
#dashboard

  .row
    .slider
      %ul.slides
        - SustainableDevelopmentGoal.all.each do |goal|
          %li
            %a.slider-item{href: goal_path(goal.url)}
              = image_tag "sdg_presenters/#{goal.number}.jpg"
              .caption.right-align
                %p.light.grey-text.text-lighten-3= goal.title
              .small-sdg-logo
                %svg{class: "ods#{goal.number}-menu"}
                  %use.menu-item{"xlink:href" => "#ODS#{goal.number}"}
  .row#sdgs
    .col.s12
      %h3 Proyectos por ODS
      #by-sdg
        = render 'by_sdg'
        %svg#sdg-chart
  .divider#dashboard
  .row#charts
    .col.m12.l4
      %h3 Proyectos por provincia
      #map
        = render 'map'
    .col.m12.l4
      %h3 Proyectos por población
      #population
        %svg
    .col.m12.l4
      %h3 Proyectos subidos en total
      %h2.count{style:"font-size:40px"}= @total
      #timeline.d-none
  .row
    .col.s12.center-align
      = link_to public_projects_path, class: "btn btn-large", id: "go-to-list" do
        %i.material-icons search
        Ir al listado de proyectos

      = link_to new_user_registration_path, class: "btn btn-large", id: "add-your-org" do
        %i.material-icons person_add
        Agregá tu organización

:javascript
  var projects_by_location = #{@by_location.to_json};
  var projects_by_sdg = #{@by_sdg.to_json};
  var projects_by_population = #{@by_population.to_json};
  var labels = #{Population.labels.to_json};
  var projects_by_upload_date = #{@by_time.to_json};
  var projects_by_organization = #{@by_organization.to_json};

  $('.count').each(function () {
    $(this).prop('Counter',0).animate({
        Counter: $(this).text()
    }, {
        duration: 4000,
        easing: 'swing',
        step: function (now) {
            $(this).text(Math.ceil(now));
        }
    });
  });

app/views/projects/edit.html.haml
%h2 Editar proyecto

- if !current_user.admin && !@project.published
  .row
    .col.s12.m6
      %i.material-icons.red-text warning︎
      Este proyecto está pendiente de aprobación.
- if !current_user.admin && @project.published
  .row
    .col.s12.m6
      %p
        %i.material-icons.green-text check
        Este proyecto está publicado y es visible al público
      %p
        %i.material-icons.red-text warning︎
        Si realiza cambios, el proyecto va a volver a estado "no publicado" hasta que reciba revisión y vuelva a ser aprobado.


= render 'form'

app/views/projects/index.html.haml
.title
  %h2
    - if current_user.is_admin
      Proyectos
    - else
      Proyectos de
      = current_user.organization.name
    = link_to new_project_path, class: "btn-floating btn-large right" do
      %i.material-icons add

- if !current_user.admin && !current_user.organization.accepted
  .row
    .col.s12
      %i.material-icons.red-text warning︎
      Tu organización necesita autorización de RACI antes de aparecer en el portal público. Podés cargar proyectos, pero estos también quedarán pendientes de aprobación.

= render_listing :projects

app/views/projects/new.html.haml
%h2 Cargar proyecto

= render 'form'

app/views/projects/public.haml
= form_tag public_projects_path, method: :get, html: {name: "filter-form"} do
  #filters
    .row#sdg-filters
      .col.s12.center-align
        - SustainableDevelopmentGoal.all.each do |goal|
          - no_filter = @filters.sustainable_development_goal.blank?
          - selected = @filters.sustainable_development_goal == goal.number.to_s || no_filter
          %a.filter-menu{href: "javascript:void(0)", "data-number" => goal.number}
            %svg{class: "ods#{goal.number}-menu"}
              %use{class: (no_filter ? "no-filter ":"") + (selected ? "":"inactive ") + "menu-item", "xlink:href" => "#ODS#{goal.number}"}
        = hidden_field_tag :sustainable_development_goal, @filters.sustainable_development_goal, id: "sdg-select"
    .row{style:"margin-bottom: 4rem;"}
      .input-field.col.s6.m4.l2
        %i.material-icons.prefix location_on
        = text_field_tag :location, @filters.location
        = active_label_tag :location, "Ubicación", @filters
      .input-field.col.s6.m4.l2
        %i.material-icons.prefix people
        = text_field_tag :population, @filters.population
        = active_label_tag :population, "Población", @filters
      .input-field.col.s6.m4.l2
        %i.material-icons.prefix today
        = text_field_tag :start_date, @filters.start_date
        = active_label_tag :start_date, "Año de inicio", @filters
      .input-field.col.s6.m4.l2
        = text_field_tag :end_date, @filters.end_date
        = active_label_tag :end_date, "Año de fin", @filters
      .input-field.col.s6.m4.l2
        %i.material-icons.prefix folder
        = text_field_tag :name, @filters.name
        = active_label_tag :name, "Nombre", @filters
      .input-field.col.s6.m4.l2
        %i.material-icons.prefix group_work
        = text_field_tag :organization, @filters.organization
        = active_label_tag :organization, "Organizacion", @filters
      .input-field.col.s6.m4.l2
        = check_box_tag :legally_formed, true, @filters.legally_formed
        = label_tag :legally_formed, "Inscripción legal"
      .input-field.col.s6{style:"margin-top: 2rem; text-align: center;"}
        = button_tag "Buscar", class:"btn waves-effect waves-light"

  = render 'public_projects_page', projects: @projects, total: @total

  .row
    .col.s12.center-align
      = hidden_field_tag :page, @filters.page, id: "page"
      - unless @filters.page.to_i == 1
        = link_to "Volver", '#', class: 'btn btn-flat btn-large', id: "previous"
      - unless @filters.page.to_i == (@total.to_f / @page_size).ceil
        = link_to "Más resultados", '#', class: 'btn btn-large', id: "more-results"


:javascript
  var options = {
    data: #{@organizations},
    list: {
      match: {
        enabled:true
      }
    }
  };
  $("#organization").easyAutocomplete(options);
  $("#organization").on("focus", function(){
    $('label[for="organization"]').addClass("active")
  });

:css
  .easy-autocomplete {
    width: unset;
    margin-left: 2rem;
  }
  .easy-autocomplete-container ul li div {
    word-break: normal;
  }
  .easy-autocomplete input[placeholder="Organización"] {
    color: #9e9e9e;
  }