config/routes.rb
Rails.application.routes.draw do
  mount Listings::Engine => "/listings"

  resources :projects, except: [:show]
  resources :organizations, except: [:new, :show]
  devise_for :users, :controllers => {:registrations => "registrations"}
  get "admin", to: 'projects#index'

  get 'sobre_la_plataforma', to: 'application#about', as: 'about'
  get "ods/:goal", to: 'sustainable_development_goals#detail', as: 'goal'
  get "proyectos", to: 'projects#public', as: 'public_projects'

  root 'projects#dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_nav_links.haml
%li
  = link_to 'Proyectos', projects_path
- if current_user.is_admin
  %li
    = link_to 'Organizaciones', organizations_path
- else
  %li
    = link_to 'Mi organización', edit_organization_path(current_user.organization)
%li
  = link_to "Salir", destroy_user_session_path, method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}/
    %title Plataforma de Sociedad Civil para el cumplimiento de los ODS
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

-show_menu = user_signed_in? && !(params[:controller] == 'projects' && (params[:action] == 'public' || params[:action] == 'dashboard')) && !(params[:controller] == 'sustainable_development_goals') && !(params[:controller] == 'application')
%body{"data-feedly-mini" => "yes", "data-gr-c-s-loaded" => "true"}
  #full-content
    %nav.white{:role => "navigation"}
      .container
        .nav-wrapper
          = link_to root_path do
            #logo-container.brand-logo
              = image_tag 'RACI-logo.png', class: 'raci'
              #logo-separator
              - unless show_menu
                .slogan.hide-on-med-and-down
                  El primer espacio que visibiliza los proyectos
                  %br
                  de todas las organizaciones sociales de Argentina
                  %br
                  y su contribución al cumplimiento de los Objetivos de Desarrollo Sostenible
              = image_tag 'sdg_logo.png', class: 'sdg hide-on-med-and-down' if show_menu
              = image_tag 'sdg_logo_mobile.png', class: 'sdg-mobile hide-on-large-only'
          - if show_menu
            %ul.right.hide-on-med-and-down
              = render 'layouts/nav_links'
            %ul#nav-mobile.side-nav{:style => "transform: translateX(-100%);"}
              = render 'layouts/nav_links'
          - else
            .right.hide-on-med-and-down.admin-link
              = link_to admin_path do
                %i.material-icons person
                Ingresar
            .right.hide-on-med-and-down.sdg-logo
              = image_tag 'sdg_logo.png', class: 'sdg hide-on-small-only'
          - if user_signed_in?
            %a.button-collapse{"data-activates" => "nav-mobile", :href => "#"}
              %i.material-icons menu
    - goal = @goal ? "body-ods#{@goal.number}" : ""
    .container{class: "c-#{params[:controller]} #{goal}"}
      = render 'shared/ods_logos'
      - flash.each do |key, value|
        %div{:class => "alert alert-#{key}"}= value
      = content_for?(:main) ? yield(:main) : yield

  %footer.page-footer.white
    .container.hide-on-med-and-down
      .row
        .col.l6.s12
          © 2017 -
          = Raci::Application.config.version_name
          \/
          = link_to "Acerca de la plataforma", about_path
        .col.l6.s12.right-align
          Con el apoyo de
          = image_tag 'un_logo.png', class: 'footer un'
          = image_tag 'cablevision-logo.svg', class: 'footer'
          = image_tag 'fibertel-logo.svg', class: 'footer'

    .container.hide-on-large-only.center-align
      .row
        .col.s12
          Con el apoyo de
        .col.s12
          = image_tag 'un_logo.png', class: 'footer un'
          = image_tag 'cablevision-logo.svg', class: 'footer'
          = image_tag 'fibertel-logo.svg', class: 'footer'
      .row.copyright
        .col.s12
          © 2017 -
          = Raci::Application.config.version_name
          \/
          = link_to "Acerca de la plataforma", about_path

app/views/layouts/sdg.haml
- content_for :main do
  .row#sdg-menu
    .col.s12
      #menu.menu
        - SustainableDevelopmentGoal.all.each do |goal|
          = link_to goal_path(goal.url), class: 'menu-link' do
            %svg{class: "ods#{goal.number}-menu"}
              %use.menu-item{"xlink:href" => "#ODS#{goal.number}"}
  = yield
  .row
    .col.m2.s12
    .col.m10.12.small.copy
      Material extraído del
      = link_to "website de las Naciones Unidas", "http://www.un.org/sustainabledevelopment/es/", target: "_blank"
= render template: "layouts/application"